### ISSUE TITLE
A question.

### ISSUE THREAD

**Issue by Dethkiller15** [h110m/h110m#1]
Is not really an issue but... What happened to your NSFWDownloader program?

**Comment by h110m** [comment]
Wanted to make a new one that uses tauri n stuff but its still into making...
In favour of this i first archived the repo and then after a while set it to private...
I don't know if i will continue to work on the new NSFW Downloader

**Comment by Dethkiller15** [comment]
> Wanted to make a new one that uses tauri n stuff but its still into making... In favour of this i first archived the repo and then after a while set it to private... I don't know if i will continue to work on the new NSFW Downloader

For some reason I launch the program and then it doesn't allow it to get past the "updating" window. could it be because of the disabled access to the page or is it because of something else?

**Comment by h110m** [comment]
Yes it's because i set the repo on private.

**Comment by Dethkiller15** [comment]
Is there a launch option so that it can just bypass looking for an update? or even some file I could delete/modify so that it can just load?

**Comment by deadlinecode** [comment]
I dont think so
Need to look into the source code since it's been a while since i worked on it

One thing you can do is just turn off your internet and launch the app directly since when you launch the app normaly it launches the updater which would launch the programm so you can just try to find and launch the programm by hand without launching the updater

**Comment by Dethkiller15** [comment]
> I dont think so Need to look into the source code since it's been a while since i worked on it
> 
> One thing you can do is just turn off your internet and launch the app directly since when you launch the app normaly it launches the updater which would launch the programm so you can just try to find and launch the programm by hand without launching the updater

I tried it without any connection to the internet and nada. left it running for about 4 min and didnt progress.

I did attempt to do so with all of these executables.
![image](https://user-images.githubusercontent.com/49108931/218550513-c7ab0e37-f4b1-4616-83aa-80f50e362df1.png)

**Comment by h110m** [comment]
@Dethkiller15 
Made the repo public again
You should now be able to just start it i think

**Comment by Dethkiller15** [comment]
> @Dethkiller15 Made the repo public again You should now be able to just start it i think

Yes just did. Thank you.
